In [2]:
import pandas as pd
from pathlib import Path
import logging

df_Thera = pd.read_csv("main_fileter.csv")
df_Thera.head()

,ID,Function,Label encoding,Sequence,Is_natural_peptide
0,100001,"Antihypertensive,Metabolic_regulatory|Glucose_...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",AA,True
1,100002,"Antihypertensive,Antimicrobial|Antibacterial|A...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",AAA,True
2,100003,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",AAAA,True
3,100004,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...","[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",AAAAAAAAAAGIGKFLHSAKKFGKAFVGEIMNS,True
4,100005,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...","[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",AAAAAAAAAK,True

In [21]:
df_Thera = df_Thera[['Function','Sequence']]
df_Thera

,Function,Sequence
0,"Antihypertensive,Metabolic_regulatory|Glucose_...",AA
1,"Antihypertensive,Antimicrobial|Antibacterial|A...",AAA
2,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAA
3,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAAGIGKFLHSAKKFGKAFVGEIMNS
4,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAK
...,...,...
58578,Antimicrobial|Antibacterial|Anti-gram-,ykkalkklakll
58579,"Anticancer,Antimicrobial",ykqchkkGGkkGsG
58580,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",yrkkwfw
58581,Antimicrobial|Antiviral,z-LVLQTM-fmk
58582,"Anticancer,Antimicrobial|Antibacterial,Antimic...",zV

In [22]:
def filter_peptides(df):
    # 计算序列长度
    df['length'] = df['Sequence'].str.len()
    
    # 条件1: 长度在 [5, 40] 之间
    cond_length = df['length'].between(5, 50)
    
    # 条件2: X 字符比例 < 1/3
    cond_x = df['Sequence'].str.count("X") / df['length'] < (1/3)
    
    # 结合条件
    df_filtered = df[cond_length & cond_x].copy()
    
    return df_filtered.drop(columns=['length'])
# df_filtered.drop(columns=['length'])

In [23]:
df_clean = filter_peptides(df_Thera)
# df_clean['function'] = df_clean['function'].replace("Growth_regeneration", "Growth_Regeneration")
df_clean.drop_duplicates(inplace=True)
df_clean.reset_index(drop=True)
# df_clean.to_csv('therapeptides_clean.csv', index=False)

/tmp/ipykernel_1309538/128256904.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['length'] = df['Sequence'].str.len()

,Function,Sequence
0,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAAGIGKFLHSAKKFGKAFVGEIMNS
1,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAK
2,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAR
3,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAIKMLMDLVNERIMALNKKAKK
4,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAK
...,...,...
56082,Antimicrobial|Antibacterial|Anti-gram-,ykkalkklakl
56083,Antimicrobial|Antibacterial|Anti-gram-,ykkalkklakll
56084,"Anticancer,Antimicrobial",ykqchkkGGkkGsG
56085,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",yrkkwfw
56086,Antimicrobial|Antiviral,z-LVLQTM-fmk

In [27]:
df_clean['Sequence'] = df_clean['Sequence'].str.upper()
df_clean = df_clean[df_clean['Sequence'].str.match(r'^[A-Za-z]+$')]
df_clean.reset_index(drop=True)

,Function,Sequence
0,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAAGIGKFLHSAKKFGKAFVGEIMNS
1,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAK
2,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAAAR
3,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAAIKMLMDLVNERIMALNKKAKK
4,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",AAAAAAK
...,...,...
54871,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",YCYCRRRFCVCVGR
54872,Antimicrobial|Antibacterial|Anti-gram-,YKKALKKLAKL
54873,Antimicrobial|Antibacterial|Anti-gram-,YKKALKKLAKLL
54874,"Anticancer,Antimicrobial",YKQCHKKGGKKGSG
54875,"Antimicrobial|Antibacterial|Anti-gram+,Antimic...",YRKKWFW

In [30]:
df_clean.drop_duplicates(inplace=True)
df_clean.reset_index(drop=True)
df_clean.to_csv('therapeptides_clean.csv', index=False)